name: Experiment
on: [workflow_dispatch]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - id: ci
        run: echo "npm ci"
  
      - run: |
           echo "Dep 1 fails"
      - if: ${{ (success() || failure()) && steps.ci.outcome=='success' }}
        run: |
           echo "test"
      - if: ${{ (success() || failure()) && steps.ci.outcome=='success' }}
        run: echo "lint succeeded"
      - if: ${{ (success() || failure()) }}
        run: echo "lksldkd" > "test${{ github.job }}.txt"
        
